repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
      - id: black
        name: black
        entry: black
        types: [ python ]
        language_version: python3.6
        args: [ --line-length=200 ]

  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        name: autoflake
        entry: autoflake
        language: system
        types: [ python ]
        args: [ --in-place, --remove-all-unused-imports ]

  - repo: local
    hooks:
      - id: check_copyright
        name: check_copyright
        stages: [ commit ]
        entry: python check_copyright.py copyright.txt ./th2
        language: python
        pass_filenames: false
        always_run: true

default_stages: [ commit, push ]